<input type="hidden" name="u_f_a" value="@lang('trs.unrecognized_from_airport')">
<input type="hidden" name="u_t_a" value="@lang('trs.unrecognized_to_airport')">
<input type="hidden" name="u_a" value="@lang('trs.unrecognized_airport')">
<input type="hidden" name="u_airline" value="@lang('trs.unrecognized_airline')">
<input type="hidden" name="same_error" value="@lang('trs.same_error')">
<input type="hidden" name="local_error" value="@lang('trs.local_flight_error')">
<input type="hidden" name="u_d" value="@lang('trs.unrecognized_date')">
<input type="hidden" name="t_n_e" value="@lang('trs.traveler_number_error')">
<input type="hidden" name="i_w_a" value="@lang('trs.infant_with_adult')">
<input type="hidden" name="fly_from" value="@lang('trs.flying_from')">
<input type="hidden" name="fly_to" value="@lang('trs.flying_to')">
<input type="hidden" name="trs_depart_date" value="@lang('trs.depart_date')">
<input type="hidden" name="trs_return_date" value="@lang('trs.return_date')">
<input type="hidden" name="trs_adult" value="@lang('trs.adult')">
<input type="hidden" name="trs_child" value="@lang('trs.child')">
<input type="hidden" name="trs_infant" value="@lang('trs.infant')">
<input type="hidden" name="cip_min_2_day" value="@lang('trs.cip_min_2_day')">
<input type="hidden" name="passenger_counting_js" value="@lang('trs.passenger')">
<input type="hidden" name="passengers_counting_js" value="@lang('trs.passengers')">
<input type="hidden" name="trs_sunday_short" value="@lang('trs.sunday_short')">
<input type="hidden" name="trs_monday_short" value="@lang('trs.monday_short')">
<input type="hidden" name="trs_Tuesday_short" value="@lang('trs.Tuesday_short')">
<input type="hidden" name="trs_Wednesday_short" value="@lang('trs.Wednesday_short')">
<input type="hidden" name="trs_Thursday_short" value="@lang('trs.Thursday_short')">
<input type="hidden" name="trs_Friday_short" value="@lang('trs.Friday_short')">
<input type="hidden" name="trs_saturday_short" value="@lang('trs.saturday_short')">
